# Docker-compose file to setup at least three nodes as leaders
version: '3'
services:
  leader_node:
    # configuration for leader node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # port for the raft cluster
      - "8080"
      # port for the HTTP API
      - "9090"
    restart: always
    networks:
      - mainnet
    command:
      - "/kafka-broker"
      - "-state_dir=./temp"
      - "-raft=:8080"
      - "-api=:9090"

  everyone_else:
    # Configuration for everyone else
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - leader_node
    ports:
      # port for the raft cluster
      - "8080"
      # port for the HTTP API
      - "9090"
    networks:
      - mainnet
    environment:
      LEADER: leader_node
    command:
      - "/kafka-broker"
      - "-state_dir=./temp"
      - -raft=everyone_else:8080
      - -api=everyone_else:9090
      - -join=leader_node:8080
    deploy:
      replicas: 4

networks:
  mainnet:
