# Docker-compose file to setup at least three nodes as leaders
version: '3.9'

services:

  leader_node:
    # configuration for leader node
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=9090
      - RAFT_PORT=8080
    command:
      - "/kafka-broker"
      - "-state_dir=./temp"
      - "-raft=:8080"
      - "-api=:9090"
    ports:
      - 8080:8080
      - 9090:9090

  followers_1:
    # configuration for leader node
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - leader_node
    environment:
      - SERVER_PORT=9090
      - RAFT_PORT=8080
    command:
      - "/kafka-broker"
      - "-state_dir=./temp"
      - "-raft=:8080"
      - "-api=:9090"
      - "-join=:8080"
    ports:
      - 8081:8080
      - 9091:9090

  followers_2:
    # configuration for leader node
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=9090
      - RAFT_PORT=8080
    command:
      - "/kafka-broker"
      - "-state_dir=./temp"
      - "-raft=:8080"
      - "-api=:9090"
      - "-join=:8080"
    depends_on:
      - leader_node
    ports:
      - 8082:8080
      - 9092:9090
